	$(document).ready(function(){
    		$("#carrotbutton").click(function(){
       			$(".circle1").toggleClass("circle2");
    		});
    	});
    	$(document).ready(function(){
    		$("#area1").hover(function(){
    			$("#h5onaftermap").toggleClass("hide");
    			$("#A1").toggle();
    			
    		})
    	});
    	$(document).ready(function(){
    		$("#area2").hover(function(){
    			$("#K").toggle();
    			$("#h5onaftermap").toggleClass("hide");
    		})
    	});
    	$(document).ready(function(){
    		$("#area3").hover(function(){
    			$("#E").toggle();
    			$("#h5onaftermap").toggleClass("hide");
    		})
    	});
    	$(document).ready(function(){
    		$("#area4").hover(function(){
    			$("#D").toggle();
    			$("#h5onaftermap").toggleClass("hide");
    		})
    	});
    	$(document).ready(function(){
    		$("#area5").hover(function(){
    			$("#C").toggle();
    			$("#h5onaftermap").toggleClass("hide");
    		})
    	});
    	$(document).ready(function(){
    		$("#area6").hover(function(){
    			$("#B").toggle();
    			$("#h5onaftermap").toggleClass("hide");
    		});
    	});
    	$(document).ready(function(){
    		$("#area7").hover(function(){
    			$("#B6").toggle();
    			$("#h5onaftermap").toggleClass("hide");
    		})
    	});
    	$(document).ready(function(){
    		$("#area8").hover(function(){
    			$("#B3").toggle();
    			$("#h5onaftermap").toggleClass("hide");
    		})
    	});
    	$(document).ready(function(){
    		$("#tea").click(function(){
    			$("#coffedis").hide();
    			$("#teadis").toggle();
    		});
    	});
    	$(document).ready(function(){
    		$("#coffe").click(function(){
    			$("#teadis").hide();
    			$("#coffedis").toggle();
    		});
    	});